const allDreamColleges = [
  "Princeton University",
  "Columbia University",
  "Harvard University",
  "MIT (Massachusetts Institute of Technology)",
  "Yale University",
  "Stanford University",
  "University of Chicago",
  "University of Pennsylvania",
  "CalTech",
  "Duke University",
  "Johns Hopkins University",
  "Northwestern University",
  "Dartmouth College",
  "Brown University",
  "Vanderbilt University",
  "Washington University in St. Louis",
  "Cornell University",
  "Rice University",
  "University of Notre Dame",
  "University of California Los Angeles",
  "Emory University",
  "University of California Berkeley",
  "Georgetown University",
  "University of Michigan Ann Arbor",
  "Carnegie Mellon University",
  "University of Virginia",
  "University of Southern California",
  "New York University",
  "Tufts University",
  "University of California Santa Barbara",
  "University of Florida",
  "University of North Carolina Chapel Hill",
  "Wake Forest University",
  "University of California San Diego",
  "University of Rochester",
  "Boston College",
  "University of California Irvine",
  "Georgia Institute of Technology",
  "University of California Davis",
  "University of Texas at Austin",
  "William and Mary",
  "Boston University",
  "Brandeis University",
  "Case Western Reserve University",
  "Tulane University",
  "University of Wisconsin Madison",
  "University of Illinois Urbana-Champaign",
  "University of Georgia",
  "Lehigh University",
  "Northeastern University",
  "Ohio State University Columbus",
  "Pepperdine University",
  "Purdue University West Lafayette",
  "Villanova University",
  "Florida State University",
  "Rensselaer Polytechnic Institute",
  "Santa Clara University",
  "University of Miami",
  "Syracuse University",
  "University of Maryland College Park",
  "University of Pittsburgh at Pittsburgh",
  "University of Washington",
  "George Washington University",
  "Pennsylvania State University University Park",
  "Rutgers University New Brunswick",
  "University of Connecticut",
  "Worcester Polytechnic Institute",
  "Fordham University",
  "Indiana University Bloomington",
  "SMU",
  "Texas A&M University",
  "University of Massachusetts Amherst",
  "University of Minnesota Twin Cities",
  "Yeshiva University",
  "Baylor University",
  "Clemson University",
  "Loyola Marymount University",
  "Virginia Tech",
  "American University",
  "Brigham Young University Provo",
  "Gonzaga University",
  "North Carolina State University",
  "Binghamton University SUNY",
  "Colorado School of Mines",
  "Elon University",
  "Howard University",
  "Marquette University",
  "Michigan State University",
  "Stevens Institute of Technology",
  "Texas Christian University",
  "University of California Riverside",
  "University of Iowa",
  "Stony Brook University SUNY",
  "University of Buffalo SUNY",
  "University of California Merced",
  "University of Delaware",
  "University of Denver",
  "University of San Diego",
  "Auburn University",
  "University of Colorado Boulder",
  "University of Oregon",
  "University of Utah",
  "Clark University",
  "Creighton University",
  "Drexel University",
  "Loyola University Chicago",
  "Miami University Oxford",
  "New Jersey Institute of Technology",
  "Saint Louis University",
  "Temple University Philadelphia",
  "University of Arizona",
  "University of California Santa Cruz",
  "University of Illinois Chicago",
  "University of San Francisco",
  "University of South Florida",
  "University of Tennessee",
  "Arizona State University",
  "Rochester Institute of Technology",
  "SUNY College of Environmental Science and Forestry",
  "University of South Carolina",
  "University of Vermont",
  "Chapman University",
  "Illinois Institute of Technology",
  "Iowa State University of Science and Technology",
  "University of Kansas",
  "University of Missouri",
  "Clarkson University",
  "DePaul University",
  "Gallaudet University",
  "Rutger University Newark",
  "Seattle University",
  "Seton Hall University",
  "University of Dayton",
  "University of Kentucky",
  "University of Oklahoma",
  "The Catholic University of America",
  "Drake University",
  "The New School",
  "Samford University",
  "Simmons University",
  "University of La Verne",
  "University of Nebraska Lincoln",
  "University of New Hampshire",
  "University of St. Thomas",
  "University of Texas at Dallas",
  "University of the Pacific",
  "University of Tulsa",
  "Colorado State University",
  "CUNY-City College",
  "Duquesne University",
  "George Mason University",
  "Michigan Technological University",
  "Quinnipiac University",
  "Rutgers University Camden",
  "San Diego State University",
  "Thomas Jefferson University",
  "University of Alabama",
  "University of Alabama at Birmingham",
  "University of Central Florida",
  "University of Cincinnati",
  "University of Mississippi",
  "Belmont University",
  "Florida International University",
  "Hofstra University",
  "Kansas State University",
  "Mercer University",
  "Oregon State University",
  "University of Arkansas",
  "University of Hawaii Manoa",
  "University of Hawaii Hilo",
  "University of Hawaii West Oahu",
  "University of Maryland Baltimore County",
  "University of Rhode Island",
  "Adelphi University",
  "Chatham University",
  "Louisiana State University",
  "St. John's University",
  "University of Alaska Anchorage",
  "Washington State University",
  "Pacific University",
  "Florida A&M University",
  "Florida Institute of Technology",
  "University of Colorado Denver",
  "University of North Dakota",
  "University of South Dakota",
  "Utah State University",
  "Azusa Pacific University",
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Pomona College",
  "Wellesley College",
  "Bowdoin College",
  "United States Naval Academy",
  "Claremont McKenna College",
  "Carleton College",
  "Middlebury College",
  "United States Military Academy",
  "Washington and Lee University",
  "Davidson College",
  "Grinnell College",
  "Hamilton College",
  "Haverford College",
  "Barnard College",
  "Colby College",
  "Colgate University",
  "Smith College",
  "Wesleyan University",
  "United States Air Force Academy",
  "University of Richmond",
  "Vassar College",
  "Bates College",
  "Colorado College",
  "Macalester College",
  "Harvey Mudd College",
  "Soka University of America",
  "Berea College",
  "Bryn Mawr College",
  "Kenyon College",
  "Mount Holyoke College",
  "Scripps College",
  "College of the Holy Cross",
  "Pitzer College",
  "Oberlin College and Conservatory",
  "Bucknell University",
  "Lafayette College",
  "Skidmore College",
  "Whitman College",
  "Denison University",
  "Franklin & Marshall College",
  "Occidental College",
  "Thomas Aquinas College",
  "DePauw University",
  "Furman University",
  "Hillsdale College",
  "Trinity College",
  "Connecticut College",
  "Dickinson College",
  "Union College",
  "The University of the South",
  "Gettysburg College",
  "Rhodes College",
  "Spelman College",
  "St. Lawrence University",
  "Wabash College",
  "Centre College",
  "Principia College",
  "Wheaton College",
  "Bard College",
  "Lawrence University",
  "Reed College",
  "St. Olaf College",
  "Agnes Scott College",
  "Muhlenberg College",
  "St. John's College",
  "Virginia Military Institute",
  "Kalamazoo College",
  "Sarah Lawrence College",
  "Willamette University",
  "Knox College",
  "Lake Forest College",
  "Lewis and Clark College",
  "University of Puget Sound",
  "Boise State University",
  "University of Guam",
  "Cal Poly San Luis Obispo",
  "Temple University Japan",
  "Waseda University"  
];

export default allDreamColleges;
